### ISSUE TITLE
Errors in the streamer log when connecting via RTSP

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic#68] opened 2022-08-05 10:04 UTC
```
10:00:43 [  client] RtspClient_before@403         RTSP OPTIONS rtsp://172.19.32.198:554/stream=0 CSeq=2 from 172.19.32.18:43658
10:00:43 [  client] RtspClient_before@403         RTSP OPTIONS rtsp://172.19.32.198:554/stream=0 CSeq=3 from 172.19.32.18:43658
10:00:43 [  client] RtspClient_before@403         RTSP DESCRIBE rtsp://172.19.32.198:554/stream=0 CSeq=4 from 172.19.32.18:43658
10:00:43 [  client] RtspClient_on_closed_conn@636 RTSP connection closed.
10:00:43 [  static] send_file_to_user@122         File '/var/www/stream=0.gz' not found
10:00:43 [  static] send_file_to_user@122         File '/var/www/stream=0.gz' not found
10:00:43 [  client] RtspClient_before@403         RTSP OPTIONS rtsp://172.19.32.198:554 CSeq=1 from 172.19.32.18:43664
10:00:43 [  client] RtspClient_on_closed_conn@636 RTSP connection closed.
```

**Comment by widgetii** [comment] 2022-08-05 10:09
Which command do you use from client side?

**Comment by ZigFisher** [comment] 2022-08-05 11:10
I launched the streamer in the console and made a request via RTSP. 

I didn't do anything in the web interface.

**Comment by widgetii** [comment] 2022-08-05 11:40
```
10:00:43 [  static] send_file_to_user@122         File '/var/www/stream=0.gz' not found
10:00:43 [  static] send_file_to_user@122         File '/var/www/stream=0.gz' not found
```

Is from web server code, I guess your browser request this URL

**Comment by ZigFisher** [comment] 2022-08-05 17:23
No, this is a bare RTSP, on the computer from which the request is made, all browsers are closed.
The problem is repeated on two different devices.

**Comment by widgetii** [comment] 2022-08-05 18:22
Couldn't reproduce either on all my cameras or on 172.19.32.198

**Comment by ZigFisher** [comment] 2022-08-05 18:42
Experimentally, it was found out that this message appears when trying to receive an RTSP stream without a login and password.

**Comment by widgetii** [comment] 2022-08-08 08:36
Closing, because it's not an issue

**Closed by widgetii** 2022-08-08 08:36 UTC
